include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 114

linter:
  rules:
    # Disable some Very Good Analysis rules that I don't think are very good
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    sort_constructors_first: false
    flutter_style_todos: false
    one_member_abstracts: false
    prefer_single_quotes: false
    prefer_double_quotes: true
    avoid_escaping_inner_quotes: true
