name: techs_html_bindings
description: Very opinionated HTML bindings, for personal use in generating websites.
version: 1.0.0
repository: https://github.com/TechnicJelle/techs_html_bindings

environment:
  sdk: ^3.10.0

dependencies:
  html: ^0.15.6
  image: ^4.8.0
  markdown: ^7.3.1
  meta: ^1.18.2
  path: ^1.9.1

dev_dependencies:
  test: ^1.31.1
  very_good_analysis: ^10.2.0
